name = "vscode-chat"
main = "src/index.ts"
compatibility_date = "2025-12-29"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[durable_objects.bindings]]
name = "DM_ROOM"
class_name = "DmRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["DmRoom"]
